# Generated by Django 4.0.1 on 2022-01-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
